services:
    _defaults:
        autowire: true
        autoconfigure: true

    PrestaShop\CliUpgradeBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/CliUpgradeBundlea.php'
